# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('sort', models.IntegerField(unique=True)),
                ('img', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VersionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Languages')),
            ],
        ),
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(unique=True)),
                ('versions', models.CharField(max_length=100)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Platform')),
            ],
        ),
        migrations.AddField(
            model_name='versioninfo',
            name='vs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Versions'),
        ),
    ]
