# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20151229_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availableversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Versions')),
            ],
        ),
        migrations.RemoveField(
            model_name='platform',
            name='version',
        ),
        migrations.AddField(
            model_name='availableversion',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Platform'),
        ),
    ]
