# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_auto_20151230_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='versions',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
