# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_versions_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='versions',
            name='download',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
