# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioninfo',
            name='subtext',
            field=models.TextField(null=True),
        ),
    ]
